### ISSUE TITLE
Install OpenZeppelin with version tag

### ISSUE THREAD

**Issue by martriay** [argentlabs/Starknet-Scaffold#1]
Nice work on this scaffold project! I'd like to point out that [OpenZeppelin discourages `main` branch installations](https://docs.openzeppelin.com/contracts-cairo/0.8.0/#install_the_library), so we should change these lines in `contracts/Scarb.toml`:

https://github.com/argentlabs/Starknet-Scaffold/blob/eb0bb8fc86287394b185897d9cfe326fdaff7484/contracts/Scarb.toml#L14-L15

to

```toml
[dependencies.openzeppelin]
git = "https://github.com/OpenZeppelin/cairo-contracts.git"
tag = "v0.8.0"
```
